### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by rajeshsaini2115** [m4mallu/inline-tube-mate#5]
bro bot video not downloading it's show 👇
ERROR: The uploader has not made this video available in your country.
You might want to use a VPN or a proxy server (with --proxy) to workaround.

I tried many url but not working please check

**Comment by m4mallu** [comment]
post one URL here...

**Comment by m4mallu** [comment]
This is not a bug actually.
Some of the videos are uploaded with country restrictions or they may available only in specific regions. For this reason, you need to add a proxy address or use VPN to download these kinds of videos.  As of now, the repo is working fine and I didn't get any reply from you, I'm closing this issue.
