### ISSUE TITLE
Bug 😬

### ISSUE THREAD

**Issue by amanimuhammed** [m4mallu/inline-tube-mate#6]
Hello sir, when a yt url sends  it is showning "url not downloadable".  Also url got deleted automatically. When i check logs it is showing nothing as error
I trird this url: http://www.youtube.com/watch?v=Kbe3FKeCd1A

Here is error screenshot:
https://telegra.ph/file/c4b2133fdee84bc922f99.jpg

**Comment by m4mallu** [comment]
This is not a bug. Some of the YouTube URLs won't be able to download. That's Y.

**Comment by amanimuhammed** [comment]
> This is not a bug. Some of the YouTube URLs won't be able to download. That's Y.

But i can download that links from other YouTube Bot

**Comment by m4mallu** [comment]
Maybe the downloader script was different. Anyways, I'll check the URL with the bot, and let's see... may get a solution for the same.

**Comment by amanimuhammed** [comment]
Ok
